### PR TITLE
Api Routes

### PR DESCRIPTION
**Pull request by poppabear8883**
***Only Merge AFTER PR #71***

*Will need to force Travis to rebuild after the above PR has been merged. 
Tests are expected to fail until then!*

Most of the routes are duplicating most of the logic, we can
dynamically build up the routes using this method. Mapping new routes
are now easy, quick and stays consistent in structure.

This makes the `routes/api.php` obsolete, but stays to redirect devs to
the right place.

*Note: Auth (passport) middleware will have to be added later*

### CODE REVIEW

**Comment by poppabear8883** [comment]
Working on a better implementation on this last commit

**Comment by cbj4074** [comment]
This is an interesting idea. My only question is how it might affect our ability to cache routes (i.e., `php artisan route:cache`). Any idea?

**Comment by poppabear8883** [comment]
This service provider does exatly the same boot process as the RouteServiceProvider ... the routes are only dynamically being build through an extracted method. Caching should remain the same and untouched

**Comment by cbj4074** [comment]
In that case, I don't have any concerns with it. Great idea!

**Pull request merged**
