### PR TITLE
Remove price references (price handling has been moved into indiehd/velkart repository)

### PR DESCRIPTION
**Pull request by cbj4074**
This addresses the first part of #192

### CODE REVIEW

**Review by mblarsen — APPROVED** [review]
Can Money be completely removed from this repo now or is it still being used somewhere?

**Comment by cbj4074** [comment]
@mblarsen That's a good question. With these changes, I don't believe that we're using it anywhere (aside from in those tests that will break as soon as we remove `full_album_price` from that migration), but it's conceivable that we will need it for various computations, eventually.

I'm not opposed to removing it if and until we need it again, though.

**Comment by cbj4074** [comment]
Also, to be clear, I think we should merge this without breaking the tests and removing `Money`, and then it sounds like @poppabear8883 is going to take a swing at tweaking the Velkart integration to be better decoupled, at which time we can address the migration, tests, and `Money` library.

**Comment by cbj4074** [comment]
Closing and re-opening to trigger build because Travis-CI failed due to out-of-memory errors that are beyond our control, it seems.

**Pull request merged**
