### PR TITLE
Laravel 8 Upgrade

### PR DESCRIPTION
**Pull request by cbj4074**

### CODE REVIEW

**Comment by mblarsen** [comment]
The problem with the routes not being set is that the ApiRouteServiceProvider is overriding register(). Remove it and you got your routes back.

```diff
-    /**
-     * register services.
-     *
-     * @return void
-     */
-    public function register()
-    {
-        //
-    }
```

The `RouteServiceProvider` calls the `map()` function indirectly from the `register()` function by setting up a 'booting' hook. But when you override the register call this never happens.

**Comment by cbj4074** [comment]
@mblarsen Indeed you are correct! Removing that `register()` method does re-enable all the routes.

There looks to be a related issue that still causes all the methods in `ApiRouteTest` to fail. It doesn't seem like the `map()` method in `MockApiRouteServiceProvider` is ever called.

I can do a bit more digging shortly, if nothing jumps-out at you!

**Comment by mblarsen** [comment]
Oh I thought that was related to the order changes. If not I'll look again.

**Comment by cbj4074** [comment]
There was another `Order`-related issue that was causing test-failures, but I just pushed a commit that fixes that.

So, with your earlier suggestion (removing the `register()` override), and the temporary block-comment around the `Order`-related route definitions, the only failing tests are those in `ApiRouteTest`.

I'm sure you can figure it out much more quickly than I could! :)

**Comment by mblarsen** [comment]
@cbj4074 the issue was that the mock service provider wasn't registered in the app container.

ps: I don't get the feedback styleci provides at all.

**Comment by cbj4074** [comment]
@mblarsen Oh, good call! That's funny... how did it ever work indeed?!

It looks like we're back to all-green, so let's go ahead and merge this in, if it looks good to you, too.

Regarding Style-CI, it looks like it's mostly whitespace on empty lines, trailing commas, etc. I'm content just to let it commit directly to PRs to fix the issues it finds. We may find that we want to tweak the rules, though.

**Review by mblarsen — APPROVED** [review]

**Pull request merged**
