### PR TITLE
Laravel 8

### PR DESCRIPTION
**Pull request by cbj4074**
To address any lingering Laravel 8 upgrade-related issues.

It seems like we still have some issues with seeders, which probably need to be updated to reflect the factory-related changes we already made.

### CODE REVIEW

**Comment by mblarsen** [comment]
Please see commit messages and TODOs added to OrderSeeder @cbj4074

**Comment by cbj4074** [comment]
@mblarsen Sorry for the delayed response!

Your confusion is entirely well-founded, and you're not overlooking anything. I had started reworking the `Order` domain object and the associated model, repository, and controller, and started this Laravel 8 upgrade before those changes were completely finished.

I'm just getting my head back into this, and it looks like there is an as yet unmerged branch on the `docs` repo that explains the nature of these changes. Let me re-orient myself and I'll post another update late today.

**Comment by cbj4074** [comment]
Actually, the aforementioned change to `docs` was indeed merged already, and may be viewed at:

https://github.com/indiehd/docs/tree/cc6ecac678943c009943aa2403e942bc2bc4a268/velkart/domain-knowledge

I still haven't had a chance to examine that cart/order `TODO` and look into the price issue you mentioned, but I'll do that tomorrow.

FWIW, it seems like all tests are passing, as of my most recent commit.

**Comment by cbj4074** [comment]
@mblarsen Actually, let's merge this, because the scope of these changes is primarily about upgrading to Laravel 8, and the `Cart`, `Order`, and `Price` issues fall outside of that scope. I will open another Issue for those and link it here.

**Review by cbj4074 — COMMENTED** [review]
@mblarsen Do you recall why we copied `database/factories/CartFactory.php` from `indiehd/velkart` into this repository? I feel like we discussed this at some point, but can't recall our conclusions without further digging.

I ask because it looks as though `CartFactory` is an _exact_ copy from the `indiehd/velkart` repo. Why not just reference the other repository if the files are identical, and if this repository _requires_ `indiehd/velkart`?

But perhaps this question strikes at the heart of one of the fundamental changes I made recently, which was to remove the `Cart` domain object (model) completely from this repository, such that it is imported from `indiehd/velkart`. I don't believe that I conveyed the nature of this change adequately, which may be the simple explanation.

Similarly, the `OrderFactory` and `OrderStatusFactory` in this repository appear to have been copied from `indiehd/velkart`. (And in fact, the `OrderFactory` in the `indiehd/velkart` repository looks to be slightly more robust in that it resolves the order status from a contract.)

Maybe there are entirely valid reasons for this duplication, and I'd appreciate you re-explaining them to me if that's the case. :)

Thanks for all your help with this!

**Comment by cbj4074** [comment]
@mblarsen I just committed a few changes that address my previous comment.

With this PR in its current state, do you see any issues remaining? Or do you have any follow-up questions regarding any Velkart integration issues that remain unanswered?

**Comment by mblarsen** [comment]
The reason for copying the factories is that we cannot access those from velkart, but we still want factories for cart and order. 

For long term we can move the factories out of dev so that they can be used in the client code. That way any other code that uses the velkart package will be able to use the factories as well.

**Comment by mblarsen** [comment]
Hmm, it seems like they have already been moved out of `autoload-dev` so it could be that we can use the factories from velkart

**Comment by cbj4074** [comment]
> The reason for copying the factories is that we cannot access those from velkart

Do you recall the reason for that?

And do you think we're all set, and can merge this now?

FWIW, I reviewed all of the upstream changes to core Laravel files, and fixed the couple of small things that I had merged inadvertently in previous commits, and at this point, it all looks good to me.

**Comment by mblarsen** [comment]
I want to try first if we can use the factories from Velkart. Normally you cannot because they are in `auto load-dev` which is omitted when the package is used as a dependency. But I'm velkart you have included the factories in `autoload`so it should work. Will give it a try.

**Review by mblarsen — APPROVED** [review]
Looks good now that you'd gotten rid of the duplicate factories.

**Pull request merged**
